Rails:
  Enabled: true

AllCops:
  Include:
    - 'app/**/*.rb'
    - 'spec/**/*.rb'

  Exclude:
    - 'bin/*'
    - 'spec/*_helper.rb'
    - 'vendor/*'
    - 'vendor/**/*'

Layout/IndentHash:
  EnforcedStyle: 'consistent'

Layout/IndentArray:
  EnforcedStyle: 'consistent'

Layout/DotPosition:
  EnforcedStyle: 'leading'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - '**/*_spec.rb'

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/spec_helper.rb'
    - 'spec/**/*_factory.rb'
    - 'spec/support/matchers/*.rb'
    - 'spec/**/*_spec.rb'

Metrics/LineLength:
  Max: 105

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'db/migrate/**/*'
    - 'db/seeds/**/*'
    - 'app/services/slack/interactive_message/**/*'
    - 'app/services/slack/dialog_submission/**/*'

Metrics/ModuleLength:
  Exclude:
    - '**/*_spec.rb'

Naming/AccessorMethodName:
  Exclude:
    - 'app/wrappers/**/*.rb'

Naming/VariableNumber:
  EnforcedStyle: 'snake_case'

Style/Alias:
  EnforcedStyle: 'prefer_alias_method'

Style/BlockDelimiters:
  Exclude:
    - '**/*_spec.rb'

Style/DateTime:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatString:
  EnforcedStyle: 'percent'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: true

Style/NumericLiterals:
  Exclude:
    - '**/*_spec.rb'
    - '**/*_factory.rb'

Layout/MultilineMethodCallIndentation:
  Exclude:
    - 'spec/features/*'

Style/AndOr:
  Exclude:
    - 'app/forms/**/*.rb'

Lint/UnusedMethodArgument:
  Exclude:
    - 'app/validators/*_validator.rb'

Style/ClassVars:
  Enabled: false

Style/MethodMissingSuper:
  Exclude:
    - 'app/wrappers/application_wrapper.rb'

Style/MissingRespondToMissing:
  Exclude:
    - 'app/wrappers/application_wrapper.rb'

Style/StructInheritance:
  Enabled: false

Style/EmptyMethod:
  Exclude:
    - 'spec/**/*_spec.rb'
